// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ZacharyHarris_Portfolio.Data.EndtoEnd
{
    public partial class Customercustomerdemo
    {
        public string CustomerId { get; set; }
        public string CustomerTypeId { get; set; }
    }
}