// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ZacharyHarris_Portfolio.Data.EndtoEnd
{
    public partial class Employeeterritories
    {
        public short EmployeeId { get; set; }
        public string TerritoryId { get; set; }
    }
}