// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ZacharyHarris_Portfolio.Data.EndtoEnd
{
    public partial class Region
    {
        public short RegionId { get; set; }
        public string RegionDescription { get; set; }
    }
}